<a href="https://colab.research.google.com/github/Nevermetyou65/PyTorch-Exercises/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip3 install torch

In [ ]:
import torch
import numpy as np

In [ ]:
v = torch.tensor([1, 2 ,3])
print(v)

tensor([1, 2, 3])


In [ ]:
print(v.dtype)

torch.int64


In [ ]:
print(v[0])

tensor(1)


In [ ]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f)
print(f[1:])

tensor([1., 2., 3., 4., 5., 6.])
tensor([2., 3., 4., 5., 6.])


In [ ]:
print(f.dtype)
print(f.size())

torch.float32
torch.Size([6])


In [ ]:
v = torch.tensor(range(1,7))
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [ ]:
v.view(6, 1) # คล้าย reshape ใน numpy

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
v.view(3, -1) # มี -1 เหมือใน reshape ด้วย

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
print(type(v))

<class 'torch.Tensor'>


In [ ]:
a = np.arange(1, 6)
print(type(a))

tensor_cnv = torch.from_numpy(a)
print(type(tensor_cnv))
print(tensor_cnv.type())
print(tensor_cnv.dtype)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
torch.LongTensor
torch.int64


In [ ]:
numpy_cnv = tensor_cnv.numpy()
print(type(numpy_cnv))

<class 'numpy.ndarray'>
